export const contractABI = [
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: "address", name: "buyer", type: "address" },
      { indexed: true, internalType: "address", name: "owner", type: "address" },
      { indexed: true, internalType: "uint256", name: "product_id", type: "uint256" },
      { indexed: true, internalType: "uint256", name: "date", type: "uint256" },
      { indexed: false, internalType: "uint256", name: "reservationId", type: "uint256" },
    ],
    name: "TransferToContract",
    type: "event",
    signature: "0x8b65e9682320c0cc0b7525f06551a6dd8e5471bd6a5d5445d63d5428e0132f48",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: "address", name: "buyer", type: "address" },
      { indexed: true, internalType: "address", name: "owner", type: "address" },
      { indexed: true, internalType: "uint256", name: "product_id", type: "uint256" },
    ],
    name: "TransferToOwner",
    type: "event",
    signature: "0x6810a44383363f6c655b7b4bd827e3395efa504e1df1c94de2f077f101e21445",
  },
  {
    inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    name: "ReservationMapping",
    outputs: [
      { internalType: "address", name: "owner", type: "address" },
      { internalType: "address", name: "buyer", type: "address" },
      { internalType: "uint256", name: "product_id", type: "uint256" },
      { internalType: "uint256", name: "date", type: "uint256" },
      { internalType: "uint256", name: "price", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
    constant: true,
    signature: "0x30f2b689",
  },
  { stateMutability: "payable", type: "receive", payable: true },
  {
    inputs: [
      { internalType: "address", name: "owner", type: "address" },
      { internalType: "uint256", name: "product_id", type: "uint256" },
      { internalType: "uint256", name: "date", type: "uint256" },
    ],
    name: "transferToContract",
    outputs: [],
    stateMutability: "payable",
    type: "function",
    payable: true,
    signature: "0x95f847fd",
  },
  {
    inputs: [
      { internalType: "uint256", name: "reservationId", type: "uint256" },
      { internalType: "address", name: "buyer_address", type: "address" },
    ],
    name: "transferToOwner",
    outputs: [],
    stateMutability: "payable",
    type: "function",
    payable: true,
    signature: "0x39ee48f6",
  },
  {
    inputs: [],
    name: "getBalanceOfContract",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
    constant: true,
    signature: "0x22968885",
  },
  {
    inputs: [{ internalType: "address", name: "_addr", type: "address" }],
    name: "getBalanceOfAddress",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
    constant: true,
    signature: "0xa665c4a4",
  },
];

export const contractAddress = "0xd43671a8699001586DD28f5549A7B2300CC20747";
